### ISSUE TITLE
请问你用的是哪一种工具编译的，是IDF工具链还是eclipse

### ISSUE THREAD

**Issue by SunJun8** [AngelLiang/esp8266_aliyun_mqtt_app#1]

**Comment by AngelLiang** [comment]
[安信可 ESP 系列一体化开发环境](http://wiki.ai-thinker.com/ai_ide_install)：基于 Windows + Cygwin + Eclipse + GCC 的综合 IDE 环境。

搭建好以上环境后：

1. 到乐鑫官网下载ESP8266_NONOS_SDK；
2. 下载本仓库，拷贝aliyun_mqtt_app文件夹到SDK主目录，用法类似于`ESP8266_NONOS_SDK/examples`里面的工程，**本app依赖ESP8266_NONOS_SDK，不能独立编译**；
3. 导入ESP8266_NONOS_SDK到安信可IDE；
4. clean and build.

另外，ESP8266没有IDF，ESP32才有IDF。

安信可IDE使用方式参见：http://wiki.ai-thinker.com/ai_ide_use
