### ISSUE TITLE
我下载此文件成功build后，烧录bin文件后esp指示灯狂闪，无法接入阿里云，如何排查问题呢？

### ISSUE THREAD

**Issue by czweb** [AngelLiang/esp8266_aliyun_mqtt_app#2]

**Comment by AngelLiang** [comment]
「esp指示灯狂闪」——极有可能是烧写错误，**模块不断重启**。另外，不同ESP8266模块有不同的烧写规则，我用的是4MB Flash。

另外我更新了下本仓库，可重新下载再试一下。有空我再更新ESP烧写参考配置。

**Comment by czweb** [comment]
恩，我觉得也应该是烧写问题吧，已经重新下载了，build后烧写还是不行。2款8266模块都测试了，如图所示：一个nodemcu款的，一个esp-01款，都不行。
正如你所说的，焦头烂额，不知道哪里问题，看输出提示像是只要烧写2个bin文件即可，是这意思吗？烧写地址也示意了。
```
eagle.flash.bin-------->0x00000
eagle.irom0text.bin---->0x10000
```
![_20180916141439](https://user-images.githubusercontent.com/5569358/45593511-e6adb700-b9ba-11e8-9fec-e6da5e8192ba.jpg)
![_20180916141046](https://user-images.githubusercontent.com/5569358/45593492-83bc2000-b9ba-11e8-9a49-5734b7682a8f.png)
![_20180916140737](https://user-images.githubusercontent.com/5569358/45593497-933b6900-b9ba-11e8-841c-69729de12102.png)
![_20180916140829](https://user-images.githubusercontent.com/5569358/45593495-8f0f4b80-b9ba-11e8-8069-d29901015f44.png)

疯狂的报错信息
![_20180916141919](https://user-images.githubusercontent.com/5569358/45593560-b61a4d00-b9bb-11e8-9b5a-a9edea8765a3.png)

**Comment by AngelLiang** [comment]
「看输出提示像是只要烧写2个bin文件即可」——看来你不知道第一次烧写需要先烧四个文件？参考一下安信可的教程步骤：http://wiki.ai-thinker.com/esp_download#%E7%83%A7%E5%BD%95%E4%B8%8B%E8%BD%BD

安信可教程是8Mbit Flash的，注意区分。后面两个bin烧写一次后就可以不用烧写了。

编译成功说明代码基本没问题，从打印信息来看，你还没正常进入到app级别的代码。所以先试着把缺的那两个bin烧进去。

然后，可到这里下载ESP8266官方文档：
https://www.espressif.com/zh-hans/support/download/documents?keys=&field_type_tid%5B%5D=14

主要看「ESP8266 SDK 入门指南」和「ESP8266 Non-OS SDK API 参考」。启动信息「**cause:2, boot mode: (3, 7)**」之类的可以在API文档里查到。

ESP8266的开发资料一直都很乱，而且还不断更新，有时我也懒得整理了，一整理完就过时了。

其他看不出什么了，还是把安信可的那个教程细读一下。

**Comment by AngelLiang** [comment]
特烦的是，以前的「eagle.irom0text.bin 」文件烧写位置是「0x40000」，后来不知从哪个SDK版本转到了「0x10000」，然后这个是「Non-FOTA」的，还有个「FOTA」的烧写规则。。。

总之我发现按照build成功后输出的信息的烧写位置是不会错的。

**Comment by czweb** [comment]
成功了，谢谢
![_20180917122618](https://user-images.githubusercontent.com/5569358/45606103-effb5a00-ba74-11e8-8350-a1ecc21c6393.png)

**Comment by AngelLiang** [comment]
恭喜。烧写成功过一次后，以后就按这个经验来就行了。

我也重新整理了下烧写步骤，放在[ESP8266-Demos仓库的wiki](https://github.com/AngelLiang/ESP8266-Demos/wiki)里。

对了，你的烧写配置第一条，「bootv1.7.bin @ 0x00000」，可以不用打钩烧写的。只需要后面四个就行，为什么这样也能成功，估计是因为你的第二条「flash.bin @ 0x00000」覆盖了前面那个。
