### ISSUE TITLE
您知道怎么把wifi的easyconfig加进去吗？不把wifi写死，适应更多场合

### ISSUE THREAD

**Issue by czweb** [AngelLiang/esp8266_aliyun_mqtt_app#3]

**Comment by AngelLiang** [comment]
easyconfig？smartconfig？easyconfig没听说过。

可试试本项目的[smartconfig分支](https://github.com/AngelLiang/esp8266_aliyun_mqtt_app/tree/smartconfig)。功能可用，只是代码比较乱。

也可参考ESP8266-Demos的[smartconfig_wifi_app](https://github.com/AngelLiang/ESP8266-Demos/tree/master/N08-smartconfig_wifi_app)
